In [1]:
import numpy as np
import json

In [4]:

with open('./data.json', 'r', encoding='utf-8') as f:
  bmi_data = json.loads(f.read())

with open('./efficiency_data.json', 'r', encoding='utf-8') as f:
  stats_data = json.loads(f.read())

In [6]:
lakers_height = [value for data in bmi_data["Lakers"] for key, value in data.items() if key=="Height"]
lakers_weight = [value for data in bmi_data["Lakers"] for key, value in data.items() if key=="Weight"]

In [18]:
pts = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="PTS"]
reb = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="REB"]
ast = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="AST"]
stl = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="STL"]
blk = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="BLK"]
mfg = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="FGM"]
mft = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="FTM"]
tov = [value for data in stats_data["Lakers"] for key, value in data.items() if key=="TO"]

In [20]:
lakers_height_array = np.array(lakers_height)
lakers_weight_array = np.array(lakers_weight)
pts_array = np.array(pts)
reb_array = np.array(reb)
ast_array = np.array(ast)
stl_array = np.array(stl)
blk_array = np.array(blk)
mfg_array = np.array(mfg)
mft_array = np.array(mft)
tov_array = np.array(tov)



In [10]:
example_2d = [[1,1,1],[1,1,1]]
print(np.array(example_2d))

[[1 1 1]
 [1 1 1]]


In [11]:
lakers_weight_kg = lakers_weight_array * 0.454

In [12]:
lakers_height_cm = lakers_height_array * 2.54

In [13]:
def bmi_calculator(system, weight, height):
  if system == "imperial":
    BMI = weight/(height**2) * 703
  elif system == "metric":
    BMI = weight/(height**2)*10000
  return BMI

In [14]:
bmi_calculator("imperial", lakers_weight_array, lakers_height_array)

array([23.74554325, 24.82894737, 24.8430309 , 26.78707514, 26.45136823])

In [17]:
bmi_calculator("metric", lakers_weight_kg, lakers_height_cm)

array([23.769235  , 24.85372007, 24.86781765, 26.81380153, 26.47775968])

In [21]:
lakers_player_efficiency = pts_array+reb_array+ast_array+stl_array+blk_array - mfg_array - mft_array - tov_array

In [22]:
print(lakers_player_efficiency)

[ 791  689  411 1776 1105]


In [23]:
print(np.sum(lakers_height_array))

390


In [24]:
print(np.sum(lakers_weight_array))

1102


In [25]:
print(np.average(lakers_weight_array))

220.4


In [26]:
print(np.average(lakers_height_array))

78.0


In [27]:
print(lakers_weight_array.min())
print(lakers_weight_array.max())

180
253


In [28]:
print(lakers_height_array.min())
print(lakers_height_array.max())

73
82


In [29]:
print(lakers_weight_array.std())
print(lakers_height_array.std())

27.817979797246238
3.286335345030997


In [30]:
print(np.percentile(lakers_height_array, 50))
print(np.percentile(lakers_height_array, 75))
print(np.percentile(lakers_height_array, 90))

78.0
81.0
81.6


In [31]:
print(np.percentile(lakers_weight_array, 50))
print(np.percentile(lakers_weight_array, 75))
print(np.percentile(lakers_weight_array, 90))

215.0
250.0
251.8
